/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import java.util.ArrayList;
import java.util.List;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import controlador.Conexion;
import java.sql.Connection;
import modelo.Equipo_futbol;
import modelo.Partido;


public class Inter_fecha_calendario extends javax.swing.JInternalFrame {
Conexion con=new Conexion();    
Connection cn;
Statement st;
ResultSet rs;
DefaultTableModel modelo;
int id;
 
    public Inter_fecha_calendario() {
        initComponents();
         listar();
    }
    
    void listar(){
    String sql="Select * from fecha_calendario";
    try{
        cn=con.getConnection();
        st=cn.createStatement();
        rs=st.executeQuery(sql);
        Object[]calendario=new Object[6];
        modelo=(DefaultTableModel)table_calendario.getModel();
        while(rs.next()){
            calendario[0]=rs.getInt("id");
            calendario[1]=rs.getInt("hora_partido");
            calendario[2]=rs.getDate("fecha_partido");
            calendario[3]=rs.getString("lugar_partido");
            calendario[4]=rs.getString("equipo_local");
            calendario[5]=rs.getString("equipo_rival");            
            modelo.addRow(calendario);
        }
        table_calendario.setModel(modelo);
    }
    catch(Exception e){
        
    }
} 
    void eliminar() {
    int filaseleccionada = table_calendario.getSelectedRow();
    if (filaseleccionada == -1) {
        JOptionPane.showMessageDialog(null, "Debe seleccionar una fila");
    } else {
        DefaultTableModel modelo = (DefaultTableModel)table_calendario.getModel();
        String id = modelo.getValueAt(filaseleccionada, 0).toString(); // Obtiene el valor de la columna "id" de la fila seleccionada

        String sql = "DELETE FROM fecha_calendario WHERE id = " + id;
        try {
            cn = con.getConnection(); // Asegúrate de que la conexión a la base de datos está establecida correctamente
            st = cn.createStatement();
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Usuario eliminado con éxito");
            modelo.removeRow(filaseleccionada); // Remueve la fila seleccionada del modelo de la tabla
            modelo.setRowCount(0); // Limpiar la tabla
        } catch (Exception e) {
            // Manejar la excepción adecuadamente
        }
    }
}
    
void agregar(){
    String horapartido=text_box_hora_partido.getText();
    String fechapartido=fecha_partido.getDateFormatString();
    String lugarpartido=text_box_lugar_partido.getText();
    String equipolocal=(String)combo_box_equipo_local.getSelectedItem();
    String equiporival=(String)combo_box_equipo_rival.getSelectedItem();
    
    if(horapartido.equals("")||fechapartido.equals("")){
        JOptionPane.showMessageDialog(null,"las cajas estan vacias");
    }
    else{
     String sql = "INSERT INTO fecha_calendario (hora_partido,  fecha_partido,lugar_partido, equipo_local, equipo_rival\n" +
             "VALUES ('" + horapartido + "','" + fechapartido + "','" + lugarpartido + "','" + equipolocal + "')";

     try{
         cn=con.getConnection();
         st=cn.createStatement();
         st.executeUpdate(sql);
          DefaultTableModel modelo = (DefaultTableModel) table_calendario.getModel();
            modelo.setRowCount(0); // Limpiar la tabla
     }
     catch(Exception e){
         
     }
    }
    } 
     
    private void llenarFilas() {
            
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        fecha_partido = new com.toedter.calendar.JDateChooser();
        text_box_hora_partido = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        combo_box_equipo_local = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        combo_box_equipo_rival = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        text_box_lugar_partido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        boton_limpiar_calendario = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        boton_editar = new javax.swing.JButton();
        boton_borrar_calendario = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_calendario = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        boton_limpiar_calendario1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Ingreso fecha calendario");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        jLabel3.setText("Hora del partido:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));
        jPanel1.add(fecha_partido, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 160, -1));
        jPanel1.add(text_box_hora_partido, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 160, -1));

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 20)); // NOI18N
        jLabel1.setText("Ingreso");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        jLabel4.setText("Fecha del partido:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        combo_box_equipo_local.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mushuc Runa", "Emelec", "Barcelona ", "Independiente", "Aucas", "Delfin", "Dep. Cuenca" }));
        jPanel1.add(combo_box_equipo_local, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 161, -1));

        jLabel8.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        jLabel8.setText("Equipo Rival:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, 20));

        combo_box_equipo_rival.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Independiente", "Aucas", "Delfin", "Emelec", "Barcelona ", "Dep. Cuenca", "Mushuc Runa", " " }));
        jPanel1.add(combo_box_equipo_rival, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 160, -1));

        jLabel5.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        jLabel5.setText("Lugar del partido:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        text_box_lugar_partido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_box_lugar_partidoActionPerformed(evt);
            }
        });
        jPanel1.add(text_box_lugar_partido, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 159, -1));

        jLabel6.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        jLabel6.setText("Equipo Local:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        boton_limpiar_calendario.setBackground(new java.awt.Color(153, 255, 204));
        boton_limpiar_calendario.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        boton_limpiar_calendario.setText("Guardar");
        boton_limpiar_calendario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_limpiar_calendarioActionPerformed(evt);
            }
        });
        jPanel1.add(boton_limpiar_calendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 170, -1));

        jLabel10.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        jLabel10.setText("*Seleccione un registro para efectuar alguna accion de edicion o borrado* ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, -1));

        boton_editar.setBackground(new java.awt.Color(255, 255, 102));
        boton_editar.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        boton_editar.setText("Editar");
        boton_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_editarActionPerformed(evt);
            }
        });
        jPanel1.add(boton_editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, 90, -1));

        boton_borrar_calendario.setBackground(new java.awt.Color(255, 51, 51));
        boton_borrar_calendario.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        boton_borrar_calendario.setText("Borrar");
        boton_borrar_calendario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_borrar_calendarioActionPerformed(evt);
            }
        });
        jPanel1.add(boton_borrar_calendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 420, 95, -1));

        table_calendario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Hora", "Fecha", "Lugar", "Equipo Local", "Equipo Rival"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_calendario);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 757, 281));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo blanco.jpg"))); // NOI18N
        jLabel13.setText("jLabel5");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 300, 320));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo blanco.jpg"))); // NOI18N
        jLabel14.setText("jLabel5");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 770, 440));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/utea.png"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 520));

        boton_limpiar_calendario1.setBackground(new java.awt.Color(153, 255, 204));
        boton_limpiar_calendario1.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        boton_limpiar_calendario1.setText("Limpiar");
        boton_limpiar_calendario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_limpiar_calendario1ActionPerformed(evt);
            }
        });
        jPanel1.add(boton_limpiar_calendario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 88, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1105, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_limpiar_calendario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_limpiar_calendario1ActionPerformed

      agregar();
       listar();
    }//GEN-LAST:event_boton_limpiar_calendario1ActionPerformed

    private void boton_editarActionPerformed(java.awt.event.ActionEvent evt) {
      
        
    }// GEN-LAST:event_boton_editarActionPerformed

    private void boton_limpiar_calendarioActionPerformed(java.awt.event.ActionEvent evt) {
      
    }// GEN-LAST:event_boton_limpiar_calendarioActionPerformed

    private void boton_borrar_calendarioActionPerformed(java.awt.event.ActionEvent evt) {
       eliminar();
       listar();
        // GEN-FIRST:event_boton_borrar_calendarioActionPerformed
    }// GEN-LAST:event_boton_borrar_calendarioActionPerformed

    private void boton_buscar_calendarioActionPerformed(java.awt.event.ActionEvent evt) {
        // GEN-FIRST:event_boton_buscar_calendarioActionPerformed
    }// GEN-LAST:event_boton_buscar_calendarioActionPerformed

    private void boton_guardar_calendarioActionPerformed(java.awt.event.ActionEvent evt) {
       agregar();
       listar();
// GEN-FIRST:event_boton_guardar_calendarioActionPerformed
    }// GEN-LAST:event_boton_guardar_calendarioActionPerformed

    private void text_field_id_calendarioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_text_field_id_calendarioActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_text_field_id_calendarioActionPerformed

    private void text_field_buscarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_text_field_buscarActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_text_field_buscarActionPerformed

    private void text_box_lugar_partidoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_text_box_lugar_partidoActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_text_box_lugar_partidoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_borrar_calendario;
    private javax.swing.JButton boton_editar;
    private javax.swing.JButton boton_limpiar_calendario;
    private javax.swing.JButton boton_limpiar_calendario1;
    private javax.swing.JComboBox<String> combo_box_equipo_local;
    private javax.swing.JComboBox<String> combo_box_equipo_rival;
    private com.toedter.calendar.JDateChooser fecha_partido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_calendario;
    private javax.swing.JFormattedTextField text_box_hora_partido;
    private javax.swing.JTextField text_box_lugar_partido;
    // End of variables declaration//GEN-END:variables

    
}
