/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

import java.util.ArrayList;
import java.util.List;

import modelo.Rol;
import modelo.TipoBusquedaCombo;
import modelo.Usuario;

public class Inter_ingreso_usuarios extends javax.swing.JInternalFrame {
    
    public ArrayList<Usuario> list_user = new ArrayList<>();
    private Usuario usuario = null;
    public Inter_ingreso_usuarios() {
        initComponents();
        llenarTabla();
    }
    
    private void llenarLista()
    {
        usuario = new Usuario(1, "Xavier", "Arellano", "xvier_arellano", "123456", 
                "xvier_arellano@example.com", 1, "Presidente");
        list_user.add(usuario);
        
        usuario = new Usuario(2, "Karla", "Soria", "karla_soria", "123456", 
                "krl_soria@example.com", 2, "Secretaria");
        list_user.add(usuario);
        
        usuario = new Usuario(3, "Miguel", "Toledo", "miguell_toledo", "123456", 
                "miguel.toledo@example.com", 3, "Arbitro");
        list_user.add(usuario);
        
        usuario = new Usuario(4, "Ramiro", "Trejo", "trejo_ramiro", "123456", 
                "ramiro.trjo@example.com", 3, "Arbitro");
        list_user.add(usuario);
        
        usuario = new Usuario(5, "Hector", "Lara", "heclara", "235689",
                "heclarasot@example.com", 3, "Arbitro");
        list_user.add(usuario);
        
        usuario = new Usuario(6, "Juan", "Calderon", "juan_cald", "2569874",
                "juan.calderon@example.com", 3, "Arbitro");
        list_user.add(usuario);
    }
    
    private void llenarTabla()
    {
        llenarLista();
                
        for (int fila = 0; fila <list_user.size(); fila++)
        {
            usuario = (Usuario)list_user.get(fila);
            llenarFilas(fila, usuario);                        
        }
        
    }
    
    private void llenarFilas(int fila, Usuario usuario) {
        DefaultTableModel tabla = (DefaultTableModel)table_usuarios.getModel();
        
        tabla.addRow(new Object[1]);
        table_usuarios.setValueAt(fila+1, fila, 0);
        table_usuarios.setValueAt(usuario.getNombre(), fila, 1);
        table_usuarios.setValueAt(usuario.getApellido(), fila, 2);
        table_usuarios.setValueAt(usuario.getNombre_usuario(), fila, 3);
        table_usuarios.setValueAt(usuario.getEmail(), fila, 4);
        table_usuarios.setValueAt(usuario.getNombre_rol(), fila, 5);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        text_email = new javax.swing.JTextField();
        lbl_ver = new javax.swing.JLabel();
        text_contrasenia = new javax.swing.JPasswordField();
        jLabel27 = new javax.swing.JLabel();
        text_nombre = new javax.swing.JTextField();
        text_apellido = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        text_nombre_user = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        boton_guardar = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        boton_limpiar = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        boton_borrar = new javax.swing.JButton();
        combo_box_buscar = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_usuarios = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        text_field_buscar = new javax.swing.JTextField();
        boton_buscar_secretaria = new javax.swing.JButton();
        boton_editar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        combo_box_rol = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setTitle("Ingreso secretaria");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        jLabel23.setText("Contraseña:");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));
        jPanel1.add(text_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 190, -1));

        lbl_ver.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        lbl_ver.setText("Ver");
        lbl_ver.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbl_ver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_verMouseClicked(evt);
            }
        });
        jPanel1.add(lbl_ver, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 20, 20));
        jPanel1.add(text_contrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 170, -1));

        jLabel27.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        jLabel27.setText("Email:");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, 30));

        text_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_nombreActionPerformed(evt);
            }
        });
        jPanel1.add(text_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 190, -1));
        jPanel1.add(text_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 190, -1));

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 20)); // NOI18N
        jLabel1.setText("Ingreso");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));
        jPanel1.add(text_nombre_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 190, -1));

        jLabel28.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        jLabel28.setText("Nombre :");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        boton_guardar.setBackground(new java.awt.Color(0, 255, 102));
        boton_guardar.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        boton_guardar.setText("Guardar");
        boton_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_guardarActionPerformed(evt);
            }
        });
        jPanel1.add(boton_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 92, -1));

        jLabel21.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        jLabel21.setText("Apellido:");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        boton_limpiar.setBackground(new java.awt.Color(153, 255, 204));
        boton_limpiar.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        boton_limpiar.setText("Limpiar");
        boton_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_limpiarActionPerformed(evt);
            }
        });
        jPanel1.add(boton_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 92, -1));

        jLabel22.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        jLabel22.setText("Nombre usuario:");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        boton_borrar.setBackground(new java.awt.Color(255, 51, 51));
        boton_borrar.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        boton_borrar.setText("Borrar");
        boton_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_borrarActionPerformed(evt);
            }
        });
        jPanel1.add(boton_borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, 80, -1));

        combo_box_buscar.setModel(new javax.swing.DefaultComboBoxModel<>());
        jPanel1.add(combo_box_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 145, -1));

        table_usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Nombre", "Apellido", "Username", "Email", "Rol"
            }
        ));
        jScrollPane1.setViewportView(table_usuarios);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 730, 280));

        jLabel10.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        jLabel10.setText("*Seleccione un registro para efectuar alguna accion de edicion o borrado* ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));

        jLabel11.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        jLabel11.setText("Buscar por:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, -1, -1));

        text_field_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_field_buscarActionPerformed(evt);
            }
        });
        text_field_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_field_buscarKeyPressed(evt);
            }
        });
        jPanel1.add(text_field_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, 157, -1));

        boton_buscar_secretaria.setBackground(new java.awt.Color(0, 102, 204));
        boton_buscar_secretaria.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        boton_buscar_secretaria.setText("Buscar");
        boton_buscar_secretaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_buscar_secretariaActionPerformed(evt);
            }
        });
        jPanel1.add(boton_buscar_secretaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 60, -1, -1));

        boton_editar.setBackground(new java.awt.Color(255, 255, 102));
        boton_editar.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        boton_editar.setText("Editar");
        boton_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_editarActionPerformed(evt);
            }
        });
        jPanel1.add(boton_editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 410, 85, -1));

        jLabel2.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        jLabel2.setText("Rol:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, 30));

        combo_box_rol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Secretaria", "Arbitro", "Trabajador" }));
        combo_box_rol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_box_rolActionPerformed(evt);
            }
        });
        jPanel1.add(combo_box_rol, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 190, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo blanco.jpg"))); // NOI18N
        jLabel6.setText("jLabel5");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 330, 340));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo blanco.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 760, 450));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/utea.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("Ingreso usuarios");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_verMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_verMouseClicked
    }//GEN-LAST:event_lbl_verMouseClicked

    private void combo_box_rolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_box_rolActionPerformed
    }//GEN-LAST:event_combo_box_rolActionPerformed

    private void boton_guardarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_boton_guardarActionPerformed
    }// GEN-LAST:event_boton_guardarActionPerformed

    private void boton_limpiarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_boton_limpiarActionPerformed
    }// GEN-LAST:event_boton_limpiarActionPerformed

    private void boton_editarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_boton_editarActionPerformed
    }// GEN-LAST:event_boton_editarActionPerformed

    private void boton_borrarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_boton_borrarActionPerformed
    }// GEN-LAST:event_boton_borrarActionPerformed

    private void text_field_buscarKeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_text_field_buscarKeyPressed

    }// GEN-LAST:event_text_field_buscarKeyPressed

    private void boton_buscar_secretariaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_boton_buscar_secretariaActionPerformed
    }// GEN-LAST:event_boton_buscar_secretariaActionPerformed

    private void text_nombreActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_text_nombreActionPerformed
    }// GEN-LAST:event_text_nombreActionPerformed

    private void text_field_buscarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_text_field_buscarActionPerformed
    }// GEN-LAST:event_text_field_buscarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_borrar;
    private javax.swing.JButton boton_buscar_secretaria;
    private javax.swing.JButton boton_editar;
    private javax.swing.JButton boton_guardar;
    private javax.swing.JButton boton_limpiar;
    private javax.swing.JComboBox<String> combo_box_buscar;
    private javax.swing.JComboBox<String> combo_box_rol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_ver;
    private javax.swing.JTable table_usuarios;
    private javax.swing.JTextField text_apellido;
    private javax.swing.JPasswordField text_contrasenia;
    private javax.swing.JTextField text_email;
    private javax.swing.JTextField text_field_buscar;
    private javax.swing.JTextField text_nombre;
    private javax.swing.JTextField text_nombre_user;
    // End of variables declaration//GEN-END:variables

}
